//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18120017_TripleNApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDATHANG = new HashSet<CHITIETDATHANG>();
        }
    
        public string MaDon { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<double> PhiVanChuyen { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANG { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
