//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18120017_TripleNApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripleNDatabaseEntities : DbContext
    {
        public TripleNDatabaseEntities()
            : base("name=TripleNDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDATHANG> CHITIETDATHANG { get; set; }
        public virtual DbSet<DONHANG> DONHANG { get; set; }
        public virtual DbSet<HINHANHSANPHAM> HINHANHSANPHAM { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<KICHTHUOCSANPHAM> KICHTHUOCSANPHAM { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAM { get; set; }
        public virtual DbSet<MAUSACSANPHAM> MAUSACSANPHAM { get; set; }
        public virtual DbSet<NGUONNHAP> NGUONNHAP { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<THONGBAONHAPHANG> THONGBAONHAPHANG { get; set; }
    }
}
