//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18120017_TripleNApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUONNHAP()
        {
            this.SANPHAM = new HashSet<SANPHAM>();
        }
    
        public string MaNguon { get; set; }
        public string TenNguon { get; set; }
        public string DiaChi { get; set; }
        public string LinkNguon { get; set; }
        public Nullable<double> TongTienNhap { get; set; }
        public Nullable<int> TongSanPhamNhap { get; set; }
        public Nullable<bool> YeuThich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM { get; set; }
        public virtual THONGBAONHAPHANG THONGBAONHAPHANG { get; set; }
    }
}
