//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18120017_TripleNApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDATHANG = new HashSet<CHITIETDATHANG>();
            this.HINHANHSANPHAM = new HashSet<HINHANHSANPHAM>();
            this.KICHTHUOCSANPHAM = new HashSet<KICHTHUOCSANPHAM>();
            this.MAUSACSANPHAM = new HashSet<MAUSACSANPHAM>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaLoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> TrongLuong { get; set; }
        public Nullable<int> SoLuongDaBan { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<double> PhanTramChi { get; set; }
        public string MaNguon { get; set; }
        public Nullable<int> SoLuongToiThieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANHSANPHAM> HINHANHSANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHTHUOCSANPHAM> KICHTHUOCSANPHAM { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAUSACSANPHAM> MAUSACSANPHAM { get; set; }
        public virtual NGUONNHAP NGUONNHAP { get; set; }
    }
}
